### PR TITLE
template updates for diagrams

### PR DESCRIPTION
**Pull request by dontseyit**
I created a new jinja template for the diagram page and also created separate templates for individual diagrams used in the service template. I didn't make any changes to the service annotations, used the current for diagrams.

I used the basic flowchart and tried to add some different styles. Also, endpoints and events are ignored in diagrams if they have no consumers (so they have no role in the communication).

For now, all-services diagrams are added as a new page (Service Communications in the UI menu). Next, we should update the menu and homepage.

Below there are images to show how they look.

**About checks**
"Check template files" is failing. So, I updated the template files in a separate branch: https://github.com/ghga-de/ghga-devutil/pull/7

total_diagram
single_service_page

### CODE REVIEW

**Review by lkuchenb — CHANGES_REQUESTED** [review]
As discussed I would suggest the following changes:

* Remove the tabular REST / event descriptions in the service pages and show only the diagrams instead
* Turn the service nodes in the diagrams into hyperlinks
* Reverse arrow direction for REST diagrams

**Comment by dontseyit** [comment]
Diagrams are updated with new style. Screenshots below.

Screenshot 2023-04-13 at 16 07 16
Screenshot 2023-04-13 at 16 06 48
Screenshot 2023-04-13 at 16 06 30

**Review by lkuchenb — CHANGES_REQUESTED** [review]
Instead of the "Produces", shouldn't we list the type also on the producer side? I see that currently that would be pretty redundant, but as soon as more services publish to the same topic it would be relevant to see which service pushes which type of message to the topic.

**Comment by dontseyit** [comment]
@lkuchenb You are right that would be more clear to understand. I quickly change the Produces text with event types, please check the below images how it will look like. I will look into a more pretty way to align nodes and lines in the larger diagrams. 

Screenshot-1
Screenshot-2

**Comment by dontseyit** [comment]
@lkuchenb the branch is up-to-date with all the requested changes

**Review by lkuchenb — APPROVED** [review]

**Pull request merged**
